TPW/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include(('main.urls',"main"),namespace="main")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path,include
from main import views
from rest_framework import routers
app_name="main"


urlpatterns=[
    path('',views.index,name='index'),
    path('tasks/', views.TaskList.as_view(), name='task_list'),
    path('login',views.tologin,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.tologout,name='logout'),
    path('addStation',views.addStation,name='addStation'),
    path('prediction',views.trajectory,name='prediction'),
    path('prediction/trajectorySeries',views.trajectorySeries,name='trajectorySeries'),
    path('history',views.historyPage,name='history'),
    path('history/manageStation',views.manageStation,name="manageStation"),
    path('model',views.modelPage,name='model'),
]

main/models.py
from django.db import models

# Create your models here.
class Station(models.Model):
    stationId=models.IntegerField(verbose_name="放球站ID",unique=True,null=False)
    stationName=models.CharField(max_length=100,verbose_name="放球站")
    altitude=models.FloatField(verbose_name="海拔")
    longitude=models.FloatField(verbose_name="经度")
    latitude = models.FloatField(verbose_name="纬度")

class Sonde(models.Model):
    sondeId = models.CharField(max_length=10,verbose_name="探空仪ID",unique=True,null=False)
    description=models.CharField(max_length=200,verbose_name="描述")

class TrajectoryRecord(models.Model):
    startDatetime=models.DateTimeField()
    endDatetime=models.DateTimeField()
    stationId = models.ForeignKey('Station', on_delete=models.CASCADE
                ,to_field='stationId',verbose_name="放球站ID")
    sondeId = models.CharField(max_length=10,verbose_name="探空仪ID")

class TrajectoryData(models.Model):
    datetime = models.DateTimeField()
    pressure = models.FloatField(verbose_name="气压")
    temperature = models.FloatField(verbose_name="温度")
    humid = models.FloatField(verbose_name="湿度")
    nspeed = models.FloatField(verbose_name="北向速度")
    espeed = models.FloatField(verbose_name="东向速度")
    uspeed = models.FloatField(verbose_name="上升速度")
    longitude = models.FloatField(verbose_name="经度")
    latitude = models.FloatField(verbose_name="纬度")
    altitude = models.FloatField(verbose_name="海拔")
    trajectoryRecordId=models.ForeignKey('TrajectoryRecord', on_delete=models.CASCADE
                ,verbose_name="记录ID")
    class Meta:
        ordering = ['datetime']

class user(models.Model):
    email = models.CharField(max_length=30, unique=True)
    username=models.CharField(max_length=30)
    password = models.CharField(max_length=12)

class NextMinTrajectory(models.Model):
    longitude = models.FloatField(verbose_name="经度")
    latitude = models.FloatField(verbose_name="纬度")
    altitude = models.FloatField(verbose_name="海拔")

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import datetime
from .trajectoryPredictor import TrajectoryPredictor
import json
from random import randrange
from django.http import HttpResponse
from pyecharts.charts import Line
from pyecharts import options as opts
from .models import TrajectoryData,Station,TrajectoryRecord,NextMinTrajectory
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate,login,logout
from .manageStaion import addStation
from .serializers import NextMinTrajectorySerializer
from rest_framework import generics,status
from rest_framework.views import APIView
from rest_framework.response import Response
# Create your views here.
class TaskList(APIView):
    def get(self, request, format=None):
        tasks = NextMinTrajectory.objects.all()
        serializer = NextMinTrajectorySerializer(tasks, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        print(request.data)
        nextMinPredictor = TrajectoryPredictor()
        try:
            longitude,latitude,altitude = float(request.POST["longitude"]),float(request.POST["latitude"]),float(request.POST["altitude"])
            pressure, temperature, humid = float(request.POST["pressure"]), float(request.POST["temperature"]), float(request.POST["humid"])
            nspeed, espeed, uspeed = float(request.POST["nspeed"]), float(request.POST["espeed"]), float(request.POST["uspeed"])
            one_X = [pressure, temperature, humid, nspeed, espeed, uspeed, longitude, latitude, altitude]
            nextlongtitude,nextlatitude,nextaltitude=nextMinPredictor.makeNextMinPrediction(one_X)
            serializer = NextMinTrajectorySerializer(data={"longitude":nextlongtitude,"latitude":nextlatitude,"altitude":nextaltitude})
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except:
            return Response("参数错误", status=status.HTTP_400_BAD_REQUEST)


def index(request):
    content={}
    content['user']=request.user
    return render(request,'main/index.html',context=content)

def tologin(request):
    if request.method == 'POST':
        return login_check(request)
    else:
        return render(request, 'main/login.html',{'login_info':0})

def login_check(request):
    useremail = request.POST.get('username')
    password = request.POST.get('password')
    n=authenticate(username=useremail,password=password)
    print(n)
    if n:
        login(request,user=n)
        return HttpResponseRedirect(reverse('main:index'))
    return render(request, 'main/login.html')

def register(request):
    if request.method == 'POST':
        return register_check(request)
    else:
        return render(request, 'main/register.html')

def register_check(request):
    useremail = request.POST.get('email')
    password = request.POST.get('password')
    username=request.POST.get('username')
    u=User.objects.filter(email=useremail).first()
    if not u:
        User.objects.create_user(username=username,email=useremail,password=password)
        return HttpResponseRedirect(reverse('main:login'))
    return render(request, 'main/register.html')

def tologout(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))

@login_required
def trajectory(request):
    content = {}
    content['user'] = request.user
    global trajectoryPredictor
    trajectoryPredictor=TrajectoryPredictor()

    stations = Station.objects.all()
    content["stations"] = stations
    return render(request, 'main/trajectory.html',context=content)

@login_required
def trajectorySeries(request):
    stationId, stationName = request.POST["stationId"].split()
    stationId=int(stationId)
    pressure,temperature,humid=float(request.POST["pressure"]),float(request.POST["temperature"]),float(request.POST["humid"])
    nspeed,espeed,uspeed=float(request.POST["nspeed"]),float(request.POST["espeed"]),float(request.POST["uspeed"])
    stationObj=Station.objects.get(stationId=stationId)
    longitude,latitude=stationObj.longitude,stationObj.latitude
    altitude=float(request.POST["altitude"])
    one_X=[pressure,temperature,humid,nspeed,espeed,uspeed,longitude,latitude,altitude]

    longitudes, latitudes, altitudes=trajectoryPredictor.makeAPrediction(one_X)
    longitudes.insert(0,longitude)
    latitudes.insert(0,latitude)
    altitudes.insert(0,latitude)
    content={}
    content['user'] = request.user
    content['longitudes']=longitudes
    content['latitudes']=latitudes
    content['altitudes']=altitudes
    content['stationName']=stationObj.stationName
    content['stationLongitude'],content['stationLatitude']=longitude,latitude
    return render(request, 'main/trajectoryMap.html',context=content)

@login_required
def historyPage(request):
    return HttpResponseRedirect(reverse('main:manageStation'))

@login_required
def manageStation(request):
    content = {}
    content['user'] = request.user
    stations = Station.objects.all()
    content["longitude"] = [s.longitude for s in stations]
    content["latitude"] = [s.latitude for s in stations]
    content["altitude"] = [s.altitude for s in stations]
    content["name"] = [str(s.stationId) + str(s.stationName) for s in stations]
    content["stations"]=stations
    return render(request, 'main/manageStation.html', context=content)








@login_required
def modelPage(request):
    return render(request, 'main/model.html')

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <title>探空仪轨迹预测与可视化系统</title>
    <script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.15&key=c384ce96822e15f024eaeab9c810a51d"></script>
    <script src="//webapi.amap.com/ui/1.0/main.js"></script>
    <script src="{% static '/js/jquery-3.3.1.js' %}"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-validator/0.5.3/js/bootstrapValidator.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-validator/0.5.3/js/language/zh_CN.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="{% static '/css/font-awesome.css' %}">
    <link href="https://cdn.bootcss.com/magnific-popup.js/1.1.0/magnific-popup.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap-validator/0.5.3/css/bootstrapValidator.css" rel="stylesheet">
    <style>

            * {
              box-sizing: border-box;
            }
            body {
              margin: 0;
            }
            /* 头部样式 */
            .header {
              background-color: #f1f1f1;
              padding: 20px;
              text-align: center;
            }
            /* 导航条 */
            .topnav {
              overflow: hidden;
              background-color: #08a883;
            }
            /* 导航链接 */
            .topnav a {
              float: left;
              display: block;
              color: #f2f2f2;
              text-align: center;
              padding: 14px 16px;
              text-decoration: none;
            }
            /* 链接 - 修改颜色 */
            .topnav a:hover {
              background-color: whitesmoke;
              color: black;
            }
            /* 创建三个不相等的列 */
            .column {
              float: left;
              padding: 10px;
            }
            /* 左右两侧宽度 */
            .column.side {
              width: 10%;

            }
            /* 中间区域宽度 */
            .column.main {
              width: 80%;
                box-shadow:15px 0 15px -15px #000,
             -15px 0 15px -15px #000;
            }
            /* 列后面清除浮动 */
            .row:after {
              content: "";
              display: table;
              clear: both;
            }
            /* 响应式布局 - 宽度小于600px时设置上下布局 */
            @media screen and (max-width: 600px) {
              .column.side, .column.middle {
                width: 100%;
              }
            }
    </style>
</head>
<body>
<div>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #7386D5;">
        <a class="navbar-brand" href="#">探空仪轨迹预测与可视化系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'main:index' %}">首页 <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'main:prediction' %}">轨迹预测</a>
                <!--<a class="nav-item nav-link active" href="{% url 'main:history' %}">数据管理</a>-->
                <a class="nav-item nav-link active" href="{% url 'main:manageStation' %}">放球站管理</a>
                <a class="nav-item nav-link active" href="{% url 'main:model' %}">关于模型</a>
                {% if user.is_active == False  %}

                    <a class="nav-item nav-link active"  style="margin-left: 480px" href="{%url 'main:login'%}">登录</a>
                    <a class="nav-item nav-link active"  href="#">/</a>
                    <a class="nav-item nav-link active"  href="{%url 'main:register'%}">注册</a>
                {% else %}
                    <a class="nav-item nav-link active" style="margin-left: 480px" href="{% url 'main:logout' %}"> 你好,{{ user.username}} /  登出</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>历史-探空仪轨迹预测与数据分析平台</title>

    <!--js-->
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.15&key=c384ce96822e15f024eaeab9c810a51d"></script>

    <script src="https://cdn.bootcss.com/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>

    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>

    <!--css-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://cdn.bootcss.com/magnific-popup.js/1.1.0/magnific-popup.css" rel="stylesheet">

    <style>
            .column {
              float: left;
              padding: 10px;
            }
            /* 中间区域宽度 */
            .column.main {
              width: 80%;
            }
            /* 列后面清除浮动 */
            .row:after {
              content: "";
              display: table;
              clear: both;
            }
            /* 响应式布局 - 宽度小于600px时设置上下布局 */
            @media screen and (max-width: 600px) {
              .column.side, .column.middle {
                width: 100%;
              }
            }
            .wrapper {
                display: flex;
                width: 100%;
                align-items: stretch;
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #7386D5;margin: 0px">
        <a class="navbar-brand" href="#">探空仪轨迹预测与数据分析平台</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'main:index' %}">首页 <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'main:prediction' %}">预测</a>
                <a class="nav-item nav-link active" href="{% url 'main:history' %}">历史</a>
                <a class="nav-item nav-link active" href="{% url 'main:model' %}">模型</a>
            </div>
        </div>
    </nav>
    <div class="wrapper" style="margin: 0;padding: 0">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <ul class="list-unstyled components" style="background-color: #7386D5;">
                <li class="active">
                    <a href="{% url 'main:manageStation' %}">放球站管理</a>
                </li>
                <li class="active">
                    <a href="{% url 'main:analyzeTrajectotyInfo' %}">探空仪运动分析</a>
                </li>
                <li class="active">
                    <a href="{% url 'main:analyzeWeatherInfo' %}">气象数据统计</a>
                </li>
            </ul>
        </nav>
        <!-- Page Content Holder -->
        <div class="column main">
            <div id="weatherInfo" style="width: 100%;height:500px;"></div>
            <div id="speedInfo" style="width: 100%;height:500px;"></div>
            <div id="positionInfo" style="width: 100%;height:500px;"></div>
        </div>
    </div>
</body>
</html>
<script type="text/javascript">
    var weatherEchart=echarts.init(document.getElementById("weatherInfo"));
    var weatherOption={
        title:{
            text:"高空气象数据展示"
        },
        tooltip:{},
        legend:{
            data:["温度","湿度","气压"]
        },
        dataZoom:[{
            type: 'slider',
            xAxisIndex: 0,
            start: 10,
            end: 60
        }, {
            type: 'inside',
            xAxisIndex: 0,
            start: 10,
            end: 60
        }],
        xAxis:{
            type:"category",
            data:{{ xName|safe }}
        },
        yAxis:{
            type:"value"
        },
        series:[
            {
                name:"温度",
                type:"line",
                data:{{ temperature|safe }}
            },
            {
                name:"湿度",
                type:"line",
                data:{{ humid|safe }}

            },
            {
                name:"气压",
                type:"line",
                data:{{ pressure|safe }}
            }
        ]
    };

    var speedEchart=echarts.init(document.getElementById("speedInfo"));
    var speedOption={
        title:{
            text:"高空气象数据展示"
        },
        tooltip:{},
        legend:{
            data:["北向速度","东向速度","垂直速度"]
        },
        dataZoom:[{
            type: 'slider',
            xAxisIndex: 0,
            start: 10,
            end: 60
        }, {
            type: 'inside',
            xAxisIndex: 0,
            start: 10,
            end: 60
        }],
        xAxis:{
            type:"category",
            data:{{ xName|safe }}
        },
        yAxis:{
            type:"value"
        },
        series:[
            {
                name:"北向速度",
                type:"line",
                data:{{ nspeed|safe }}
            },
            {
                name:"东向速度",
                type:"line",
                data:{{ espeed|safe }}

            },
            {
                name:"垂直速度",
                type:"line",
                data:{{ uspeed|safe }}
            }
        ]};

    var positionEchart=echarts.init(document.getElementById("positionInfo"));
    var positionOption={
        title:{
            text:"高空气象数据展示"
        },
        tooltip:{},
        legend:{
            data:["经度","纬度","海拔"]
        },
        dataZoom:[{
            type: 'slider',
            xAxisIndex: 0,
            start: 10,
            end: 60
        }, {
            type: 'inside',
            xAxisIndex: 0,
            start: 10,
            end: 60
        }],
        xAxis:{
            type:"category",
            data:{{ xName|safe }}
        },
        yAxis:{
            type:"value"
        },
        series:[
            {
                name:"经度",
                type:"line",
                data:{{ longitude|safe }}
            },
            {
                name:"纬度",
                type:"line",
                data:{{ latitude|safe }}

            },
            {
                name:"海拔",
                type:"line",
                data:{{ altitude|safe }}
            }
        ]
    }
    weatherEchart.setOption(weatherOption);
    speedEchart.setOption(speedOption);
    positionEchart.setOption(positionOption);

    $(document).ready(function () {
                 $('#sidebarCollapse').on('click', function () {
                     $('#sidebar').toggleClass('active');
                 });
             });
</script>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="width=100%;height=20px">
        <img src="{% static '/image/world.topo.bathy.200401.jpg' %}" width="100%" height="250"></img>
    </div>
    <div class="row">
        <div class="column side"></div>
        <div class="column main">
            <h3 align="center">探空仪轨迹预测与可视化系统</h3>
            <p>  智能探空网络自适应调度管理系统利用多源数据，拟将多点探空仪、多点新型多通道探空通讯网关以及新型探空仪基测箱构成的综合决策网络，通过信息融合方法、系统决策模型及系统自适应方法，融合机器学习和数据挖掘等技术进行研究。探空仪运动轨迹预测子系统是智能探空网络自适应调度管理系统的核心部分。该系统根据历史数据，通过深度学习方法来预测探空仪在指定条件下的运动轨迹，为探空仪自适应调度提供支持。</p>
            <ul>
                <li>探空仪施放后轨迹预测和预测轨迹可视化展示</li>
                <li>放球站数据管理</li>
                <li>探空仪轨迹预测模型介绍</li>
            </ul>
        </div>
        <div class="column side"></div>
    </div>
{% endblock %}

main/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

 <form class="form-signin"  action="{% url 'main:login' %}" method="post">
     <div align="center">
        <img class="mb-4" src="{% static 'css/login/logo.png' %}" alt="" width="150" height="150">
     </div>
  <h1 class="h3 mb-3 font-weight-normal">请登录</h1>

     {% csrf_token %}
 <!--
  <label for="inputEmail" class="sr-only">电子邮箱</label>
  <input name="email" type="email" id="email" class="form-control" placeholder="电子邮箱" required autofocus>
  -->
 <label for="inputEmail" class="sr-only">用户名</label>
  <input name="username" type="text" id="inputEmail" class="form-control" placeholder="用户名" required autofocus>
  <label for="inputPassword" class="sr-only">密码</label>
  <input name="password" type="password" id="password" class="form-control" placeholder="密码" required>

    {% if login_info == 1 %}
     <div class="ececk_warning"><span>用户不存在</span></div>
     {% elif login_info == 2 %}
     <div class="ececk_warning"><span>密码错误</span></div>
    {% endif %}
     <div class="checkbox mb-3">
        <label>
        <input type="checkbox" value="remember-me"> 记住我
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
     </div>
     <div class="form_reg_btn">
         <span>还没有帐号？</span><a href="{%url 'main:register'%}">马上注册</a>
     </div>
</form>

</body>
</html>

main/templates/main/model.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="width=100%;height=20px">
        <img src="{% static '/image/world.topo.bathy.200401.jpg' %}" width="100%" height="250"></img>
    </div>
    <div class="row">
        <div class="column side"></div>
        <div class="column main">
            <h3 align="center">关于模型</h3>
            <a>基于气象部门记录的2018年6月到2019年10月共1405次施放后探空仪数据，
                保留温度、湿度、气压、南北向速度、东西向速度、垂直向速度、经度、纬度、海拔特征，
                对原始数据进行每分钟取样一次，
                选取施放后运动超过4h的探空仪数据记录，经过数据预处理后构建数据集，
                搭建并训练GRU-GRU的Encoder-Decoder模型，模型如下图所示。
                五折交叉验证下，MAE（平均绝对误差）=0.0198，MSE（均方误差）=0.0014。
            </a>
            <div class="width=50%;height=20px;" style="text-align: center">
                <img src="{% static '/image/EncoderDecoder.png' %}" width="10%" style="margin: 0 auto"></img>
            </div>
        </div>
        <div class="column side"></div>
    </div>
{% endblock %}

main/templates/main/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<form class="form-signin" action="{% url 'main:register' %}" method="post">
     <div align="center">
        <img class="mb-4" src="{% static 'css/login/logo.png' %}" alt="" width="150" height="150">
     </div>
  <h1 class="h3 mb-3 font-weight-normal">注册</h1>
    {% csrf_token %}
  <label for="inputEmail" class="sr-only">用户名</label>
  <input name="username" type="text" id="inputEmail" class="form-control" placeholder="用户名" required autofocus>
  <label for="inputEmail" class="sr-only">注册邮箱</label>
  <input name="email" type="email" id="inputEmail" class="form-control" placeholder="注册邮箱" required autofocus>
    <label name="password" for="inputPassword" class="sr-only">密码</label>
  <input name="password" type="password" id="inputPassword" class="form-control" placeholder="密码" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> 记住我
    </label>
      <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
  </div>
     <div class="form_reg_btn">
         <span>还没有帐号？</span><a href="{%url 'main:login'%}">返回登录</a>
     </div>
</form>

</body>
</html>